site:
  title: xmera Omnia Demo Guide
  url: /
  start_page: xo-demo-guide:einfuehrung:index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: .

  - url: ../xo_docs
    branches: HEAD
    start_path: .

ui: 
  bundle: 
    url: https://github.com/xmera-circle/antora-ui-omnia/releases/download/0.2.2/ui-bundle.zip
    snapshot: true
