site:
  title: xmera Omnia Demo Guide
  url: https://docs.xmera.de
  start_page: xmera-omnia-demo-guide:einfuehrung:index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD

ui: 
  bundle:
    url: https://github.com/xmera-circle/antora-ui-omnia/releases/download/0.3.0/ui-bundle.zip
    snapshot: true

output:
  clean: true
  dir: build

antora:
  extensions:
  - require: '@antora/lunr-extension'
